platform :ios, '7.0'
use_frameworks!

target '东方幼儿园测试' do

pod 'AFNetworking', 		'~> 2.5.0'
pod 'AliyunOSSiOS', 		'~> 2.3.0.1'
pod 'FXBlurView', 			'~> 1.6.3'
pod 'MBProgressHUD', 		'~> 0.9.2'
pod 'MLLabel', 				'~> 1.2'
pod 'MMDrawerController', 	'~> 0.5.7'

# MMPopupView这个库里面改了如下内容，尽量不要update。
# 1.回调block中增加了参数。
# 2.增加了禁止横屏的Controller文件，也修改了这个库在cocoapods中的引用文件。
pod 'MMPopupView', 			'~> 1.7.2'

pod 'Mantle', 				'~> 2.0.7'
pod 'Masonry',				'~> 0.6.1'
pod 'RATreeView', 			'~> 2.1.0'
pod 'JTCalendar', 			'~> 2.0'

# 下面这个ReactiveCocoa是解决了与Mantle的文件冲突的4.1版本，
# 但是4.1版本混编Xcode7会出现问题，这里先注释掉。暂时使用比较稳定的2.5版本
#	pod 'ReactiveCocoa', :podspec => 'https://gist.githubusercontent.com/PaulTaykalo/04f8e2ee25b9d57f03455ccafd541b34/raw/e94f3bec7a9450ecd0f0cdc9b4899deb0b91d758/ReactiveCocoa.podspec.json'

pod 'ReactiveCocoa', 		'~> 2.5'
pod 'TTTAttributedLabel', 	'~> 1.13.4'

end
