#source 'https://github.com/CocoaPods/Specs.git'  下载地址

platform :ios, '7.0'

def pods
    pod 'AFNetworking',         '~> 3.0.4'
    pod 'SDWebImage',           '~> 3.8.2'
    pod 'MBProgressHUD',        '~> 1.0.0'
    pod 'ASIHTTPRequest',       '~> 1.8.2'
    pod 'MJRefresh',	        '~> 3.1.12'
    pod 'FMDB',                 '~> 2.7.2'
    pod 'JPush',                '~> 3.0.9'
    pod 'IQKeyboardManager',    '~> 3.3.7'  #iOS8 and later
    
    
    
end
target 'MicroApp' do
    pods
end
